apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vehj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-vehj@sha256:56de2886a1c553ac7c2569e7ab19886525d15981a2e2a82e962cf605b9fc3e40
        name: my-nodejs
        resources: {}
status: {}
